### ISSUE TITLE
Using Node.js and require rather than ES6 import

### ISSUE THREAD

**Issue by domfee** [obartra/ssim#90]
Hi I'm trying to get this to work with `require` but currently struggling.

Any help would be really appreciated.

```js
var ssim = require("ssim.js");

ssim("/img1.jpg", "/img2.jpg")
  .then(function(out) {
      console.log("SSIM:", out.mssim, "(", out.performance, "ms)");
    })
    .catch(function(err) {
      console.error("Error generating SSIM", err);
    });
```
Error:
```
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/blah/blah/blah/blah/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by domfee** [comment]
Resolved.

**Comment by obartra** [comment]
Oops sorry I missed this, what was the issue?
